### ISSUE TITLE
'nb_features' and 'n_features', what is the difference?

### ISSUE THREAD

**Issue by kridsadakorn** [colomemaria/epiScanpy#47]
![Screen Shot 2019-11-07 at 16 13 14](https://user-images.githubusercontent.com/1006124/68401216-a3dc0f00-0179-11ea-93bc-b2de1f1e822b.png)

To follow up after the hackathon, some participants found that after epi.pp.coverage_cells and epi.pp.filter_cells, there were 'nb_features' and 'n_features' added to AnnData. What is the difference?

**Comment by DaneseAnna** [comment]
It correspond to the same measurement calculated in 2 different questions. The label was uniformded to nb_features only.
