### ISSUE TITLE
Episcanpy still using scanpy.api

### ISSUE THREAD

**Issue by le-ander** [colomemaria/epiScanpy#53]
Hi Anna,
one more thing I noticed:

Episcanpy seems to still use `scanpy.api` This will soon break episcanpy when scanpy removes the api module as announced.

This FutureWarning appears when importing scanpy:

```python
>>> import episcanpy
/app/python37/lib/python3.7/site-packages/scanpy/api/__init__.py:6: FutureWarning:

In a future version of Scanpy, `scanpy.api` will be removed.
Simply use `import scanpy as sc` and `import scanpy.external as sce` instead.

  FutureWarning,
```

**Comment by DaneseAnna** [comment]
Thank you or the warning. I am currently working on this and the scanoy+ anndata compatibility issues.
