### ISSUE TITLE
Potential dependency conflicts between episcanpy and scipy

### ISSUE THREAD

**Issue by NeolithEra** [colomemaria/epiScanpy#61]
Hi, as shown in the following full dependency graph of **_episcanpy_**, **_episcanpy_** requires **_scipy <=1.3_**, **_episcanpy_** requires **_seaborn *_** (seaborn 0.10.0 will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_seaborn 0.10.0_** transitively introduces **_scipy >=1.0.1_**.
Obviously, there are multiple version constraints set for scipy in this project. However, according to pip's “_first found wins_” installation strategy, **_scipy 1.3_** (i.e., the newest version satisfying constraint <=1.3) is the actually installed version.
Although the first found package version **_scipy 1.3_** just satisfies the later dependency constraint （**_scipy >=1.0.1_**), such installed version is very close to the upper bound of the version constraint of Scipy specified by **_seaborn 0.10.0_** .

Once **_seaborn_** upgrades，its newest version will be installed, as **_episcanpy_** does not specify the upper bound of version constraint for **_seaborn_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_seaborn_** version introduces a higher version of Scipy, violating its another version constraint **_<=1.3_**.
According to the release history of **_seaborn_**, it habitually upgrates **_Scipy_** in its recent releases. For instance, **_seaborn 0.9.0_** upgrated Scipy’s constraint from **_*_** to **_>=0.14.0_**, **_seaborn 0.9.1.rc0_**  upgrated Scipy’s constraint from **_>=0.14.0_** to **_>=0.17.1_**, and **_seaborn 0.10.0rc0_** upgrated Scipy’s constraint from **_>=0.17.1_** to **_>=1.0.1_**. 
As such, it is a warm warning of a potential dependency conflict issue for episcanpy.

### Dependency tree
```
episcanpy - 0.1.10
| +- anndata(install version:0.6.22rc1 version range:==0.6.22rc1)
| | +- h5py(install version:2.10.0 version range:*)
| | +- natsort(install version:6.2.1 version range:*)
| | +- numpy(install version:1.18.4 version range:<2,>=1.14)
| | +- pandas(install version:1.0.3 version range:>=0.23.0)
| | +- scipy(install version:1.3 version range:<2,>=1.0)
| +- bamnostic(install version:1.1.4 version range:>=1.0.12)
| +- matplotlib(install version:3.2.1 version range:>=3.0.0)
| | +- cycler(install version:0.10.0 version range:>=0.10)
| | | +- six(install version:1.14.0 version range:*)
| | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | +- numpy(install version:1.18.4 version range:>=1.11)
| | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| +- pandas(install version:1.0.3 version range:>=0.21)
| +- scanpy(install version:1.4.4 version range:==1.4.4)
| | +- anndata(install version:0.6.22rc1 version range:>=0.6.22rc1)
| | | +- h5py(install version:2.10.0 version range:*)
| | | +- natsort(install version:6.2.1 version range:*)
| | | +- numpy(install version:1.18.4 version range:<2,>=1.14)
| | | +- pandas(install version:1.0.3 version range:>=0.23.0)
| | | +- scipy(install version:1.3 version range:<2,>=1.0)
| | +- h5py(install version:2.10.0 version range:*)
| | +- importlib-metadata(install version:1.6.0 version range:>=0.7)
| | +- joblib(install version:0.14.1 version range:*)
| | +- matplotlib(install version:3.0. version range:==3.0.)
| | +- natsort(install version:6.2.1 version range:*)
| | +- networkx(install version:2.4 version range:*)
| | | +- decorator(install version:4.4.2 version range:>=4.3.0)
| | +- numba(install version:0.48.0 version range:>=0.41.0)
| | +- pandas(install version:1.0.3 version range:>=0.21)
| | +- patsy(install version:0.5.1 version range:*)
| | | +- numpy(install version:1.18.4 version range:>=1.4)
| | | +- six(install version:1.14.0 version range:*)
| | +- scikit-learn(install version:0.22.2.post1 version range:>=0.19.1)
| | +- scipy(install version:1.3 version range:>=1.3)
| | +- seaborn(install version:0.10.0 version range:*)
| | | +- matplotlib(install version:3.2.1 version range:>=2.1.2)
| | | | +- cycler(install version:0.10.0 version range:>=0.10)
| | | | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | | | +- numpy(install version:1.18.4 version range:>=1.11)
| | | | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | | | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| | | +- numpy(install version:1.18.4 version range:>=1.13.3)
| | | +- pandas(install version:1.0.3 version range:>=0.22.0)
| | | +- scipy(install version:1.3 version range:>=1.0.1)
| | +- statsmodels(install version:0.11.1 version range:>=0.10.0rc2)
| | | +- numpy(install version:1.18.4 version range:>=1.14)
| | | +- pandas(install version:1.0.3 version range:>=0.21)
| | | +- patsy(install version:0.5.1 version range:>=0.5)
| | | | +- numpy(install version:1.18.4 version range:>=1.4)
| | | | +- six(install version:1.14.0 version range:*)
| | | +- scipy(install version:1.3 version range:>=1.0)
| | +- tables(install version:3.6.1 version range:*)
| | | +- numexpr(install version:2.7.1 version range:>=2.6.2)
| | | | +- numpy(install version:1.18.4 version range:>=1.7)
| | | +- numpy(install version:1.18.4 version range:>=1.9.3)
| | +- tqdm(install version:4.45.0 version range:*)
| | +- umap-learn(install version:0.4.1 version range:>=0.3.0)
| +- scipy(install version:1.3 version range:<=1.3)
| +- seaborn(install version:0.10.0 version range:*)
| | +- matplotlib(install version:3.2.1 version range:>=2.1.2)
| | | +- cycler(install version:0.10.0 version range:>=0.10)
| | | | +- six(install version:1.14.0 version range:*)
| | | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | | +- numpy(install version:1.18.4 version range:>=1.11)
| | | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| | +- numpy(install version:1.18.4 version range:>=1.13.3)
| | +- pandas(install version:1.0.3 version range:>=0.22.0)
| | +- scipy(install version:1.3 version range:>=1.0.1) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution 
1.	Loosen the version range of **_scipy_** to be **_*_**.
2.	Remove your direct dependency **_scipy_**, and use the **_scipy_** transitively introduced by **_seaborn_**.
3.	Change your direct dependency **_seaborn_** to be **_<=0.10.0_**.
@DaneseAnna Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by DaneseAnna** [comment]
Hi, 
This is a very good point. The problem we encountered was a compatibility issue between script and h5py (if I recall correctly). The easiest is probably to go with option 3 for now. But I will have a closer look, to resolve the compatibility issues and loosen the version requirements.
