### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by farnoush-shh** [colomemaria/epiScanpy#77]
Hi! problem with importing episcanpy.api:

import episcanpy.api as epi

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-18b9f5d5285b> in <module>
----> 1 import episcanpy.api as epi

c:\users\49176\anaconda3\envs\atac\lib\site-packages\episcanpy\api\__init__.py in <module>
      8 from . import pp
      9 from . import tl
---> 10 from . import ct
     11 from . import pl
     12 

c:\users\49176\anaconda3\envs\atac\lib\site-packages\episcanpy\api\ct.py in <module>
      4 from ..count_matrix._atac_mtx import bld_atac_mtx, save_sparse_mtx
      5 from ..count_matrix._load_met_ct_mtx import load_met_noimput
----> 6 from ..count_matrix._bld_atac_mtx2 import bld_mtx_fly

ModuleNotFoundError: No module named 'episcanpy.count_matrix._bld_atac_mtx2'

there is no _mtx2 file and when I removed it manually I got another error for importing bld_mtx_fly!
Would yo please check. I am using the latest version..

**Comment by DaneseAnna** [comment]
Hi, sorry ! We forgot to update the tutorials. 
Now you just need:
 import episcanpy as epi

**Comment by farnoush-shh** [comment]
solved! thanks
