### ISSUE TITLE
Remove python 2.7 tests

### ISSUE THREAD

**Issue by yannikschaelte** [colomemaria/epiScanpy#89]
Some dependencies seem to require python >= 3.6/7, therefore it may make sense to remove the python 2.7 tests (which seem to fail), as that version is anyway no longer recommended.

**Comment by DaneseAnna** [comment]
no

**Comment by DaneseAnna** [comment]
@kridsadakorn Yannik is messing with you

**Comment by yannikschaelte** [comment]
no
