### ISSUE TITLE
Error running "epi.ct.save_sparse_mtx"

### ISSUE THREAD

**Issue by tzhu-bio** [colomemaria/epiScanpy#90]
Hello, I get an error when I run your sample code.
![image](https://user-images.githubusercontent.com/54537420/112918545-aefd5980-9137-11eb-8389-4a07334e6c91.png)

**Comment by DaneseAnna** [comment]
Hi, 

Thank you for reporting this issue. It has been fixed on the master branch of this GitHub.
It will be part of the next release of epiScanpy as well. 

Best, 
Anna
